name: Sync Airflow DAGs to EC2
on:
  push:
    paths:
      - 'airflow-dags/**'

jobs:
  sync-dags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 18.141.180.224 >> ~/.ssh/known_hosts

      - name: Sync airflow-dags to EC2
        run: |
          scp -r airflow-dags/* ec2-user@YOUR.EC2.IP:/home/ec2-user/dags/
